Resolve issue 14
elm-camp/website pull request #27
Opened 2024-02-15 22:03 UTC by jxxcarlson

This PR resolves issue #14.  Please check.

2024-02-15 22:32 UTC, katjam requested changes
Couple of typos but this looks OK. We could also replace the logo file with the new one from the prospectus.

2024-02-15 22:32 UTC, katjam commented on head.html
> +    content="An Elm unconference taking place at Coreyhaines Park . Wed 28th - Fri 30th June">
```suggestion
    content="An Elm unconference taking place at Colehayes Park, Devon UK. Tue 18th - Fri 21st June">
```

2024-02-15 22:32 UTC, katjam commented on head.html
> +    content="An Elm unconference taking place at Coreyhayes Park, Devon UK. Tue 18th - Fri 21st June">
```suggestion
    content="An Elm unconference taking place at Colehayes Park, Devon UK. Tue 18th - Fri 21st June">
```

2024-02-15 22:49 UTC, katjam commented
@jxxcarlson I added a png and webp version of the logo because I think maybe the webp version I made does not have transparent background. It's not replacing the old one on my local site, so I pushed up in the interest of time so you could have a play with it.

2024-02-16 01:18 UTC, jxxcarlson reviewed
I think it is OK now -- mess with venue spellings and dates fixed

2024-02-16 01:18 UTC, merged

2024-02-16 01:19 UTC, jxxcarlson commented
Katja, I merged this PR, please do check the result however.

2024-02-19 00:43 UTC, katjam commented
Thanks @jxxcarlson This looks great now! I changed the arrival from Weds --> Tues on `main`